kind: pipeline
name: default
type: docker


steps:
  - name: deploy-trigger
    image: plugins/downstream
    settings:
      server:
        from_secret: drone-server
      token:
        from_secret: drone-token
      fork: true
      repositories:
        - MyLassi.xyz/mylassi-deploy@master
    when:
      branch:
        - master
